"""
Django settings for image_color project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qcrn(1vvb^0y0@1x^dc#b%9k_1!@d&bvw-6tz69=)2maxz##t@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

EXTERNAL_APPS = [
    'home',
    # 'home.apps.HomeConfig',
]
INSTALLED_APPS += EXTERNAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'image_color.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'image_color.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'img_color', 'static'),
# ]


# media files
MEDIA_ROOT = BASE_DIR / "media"

MEDIA_URL = "/media/"

# # Define the base directory of the Django project
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#
# # Define the path to the model file
# MODEL_FILE_PATH = os.path.join(BASE_DIR, 'models', 'model.h5')
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Define the directory where the model file is located
# MODEL_ROOT = os.path.join(BASE_DIR, 'home', 'models')


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Define paths
# MODEL_ROOT = os.path.join(BASE_DIR, 'home', 'colimg', 'models')
# INPUT_IMAGE_ROOT = os.path.join(BASE_DIR, 'home', 'colimg', 'input')
# OUTPUT_IMAGE_ROOT = os.path.join(BASE_DIR, 'home', 'colimg', 'output')

# Define the directories for image, model JSON, and model weights
# IMAGE_DIR = os.path.join(BASE_DIR, 'media', 'uploaded_images')
# MODEL_DIR = os.path.join(BASE_DIR, 'home', 'models')
#
# # Define the paths for image, model JSON, and model weights
# IMAGE_PATH = os.path.join(IMAGE_DIR, 'uploaded_image.jpg')
# MODEL_JSON_PATH = os.path.join(MODEL_DIR, 'model.json')
# MODEL_WEIGHTS_PATH = os.path.join(MODEL_DIR, 'model.h5')
#
# # Define the output folder for colorized images
# COLORIZED_IMAGES_DIR = os.path.join(BASE_DIR, 'media', 'colorized_images')

# Define the MODEL_ROOT directory
MODEL_ROOT = os.path.join(BASE_DIR, 'home', 'models')